version: 2
jobs:
  build:
    machine:
      enabled: true

    steps:
      - checkout

      - run:
          no_output_timeout: 5h
          command: |
            df -H .
            checkout_dir=$PWD
            echo "Building in directory: $checkout_dir"
            set -euo pipefail
            build_dir_in_container=/opt/yb-build/tmp/yb-toolchain
            docker run \
              -i \
              -e GITHUB_TOKEN \
              "-w=$build_dir_in_container" \
              --mount type=bind,source="$PWD",target="$build_dir_in_container" \
                  "yugabyteci/yb_build_infra_centos7:v2020-03-28T04_39_36" \
                  bash -c "
                    set -euo pipefail
                    cd \"$build_dir_in_container\"
                    ./build_toolchain.sh
                  "
