# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build toolchain
      run: |
        set -euo pipefail
        build_dir_in_container=/root/yb-toolchain
        docker run \
          -i \
          "-w=$build_dir_in_container" \
          --mount type=bind,source="$PWD",target="$build_dir_in_container" \
              "yugabyteci/yb_build_infra_centos7:v2020-03-28T04_39_36" \
              bash -c '
                yum install -y bison gperf
                ctng_version=1.23.0
                ctng_tag=crosstool-ng-$ctng_ver
                git clone https://github.com/crosstool-ng/crosstool-ng --branch "$ctng_tag" --depth 1 "$ctng_tag"
                cd "$ctng_tag"
                ./bootstrap
                ctng_install_dir=/usr/share/$ctng_tag
                ./configure --prefix=$ctng_install_dir
                make
                make install
              '
